# docker-compose.yml
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./scripts:/code/scripts # <-- ADD THIS LINE
      - ./data:/code/data # <-- ADD THIS LINE
    depends_on:
      - redis
      - chroma
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data # Use a named volume for persistence

  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000" # IMPORTANT: Map to host port 8001 to avoid conflict with our API
    volumes:
      - chroma-data:/chroma/.chroma/index # Use a named volume for persistence

  frontend:
    build:
      context: ./ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

volumes:
  redis-data: # Define the named volume
  chroma-data: # Define the named volume
